package com.tak.freeapi


const val MOCK_VALID_CATEGORIES_RESPONSE = "[\"Animals\",\"Anime\",\"Anti-Malware\",\"Art \\u0026 Design\",\"Books\",\"Business\",\"Calendar\",\"Cloud Storage \\u0026 File Sharing\",\"Continuous Integration\",\"Cryptocurrency\",\"Currency Exchange\",\"Data Validation\",\"Development\",\"Dictionaries\",\"Documents \\u0026 Productivity\",\"Environment\",\"Events\",\"Finance\",\"Food \\u0026 Drink\",\"Fraud Prevention\",\"Games \\u0026 Comics\",\"Geocoding\",\"Government\",\"Health\",\"Jobs\",\"Machine Learning\",\"Music\",\"News\",\"Open Data\",\"Open Source Projects\",\"Patent\",\"Personality\",\"Photography\",\"Science \\u0026 Math\",\"Security\",\"Shopping\",\"Social\",\"Sports \\u0026 Fitness\",\"Test Data\",\"Text Analysis\",\"Tracking\",\"Transportation\",\"URL Shorteners\",\"Vehicle\",\"Video\",\"Weather\"]"

const val MOCK_CATEGORY_ANIMALS_RESPONSE = "{\"count\":11,\"entries\":[{\"API\":\"Cats\",\"Description\":\"Pictures of cats from Tumblr\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"unknown\",\"Link\":\"https://thecatapi.com/docs.html\",\"Category\":\"Animals\"},{\"API\":\"Dogs\",\"Description\":\"Based on the Stanford Dogs Dataset\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"yes\",\"Link\":\"https://dog.ceo/dog-api/\",\"Category\":\"Animals\"},{\"API\":\"HTTPCat\",\"Description\":\"Cat for every HTTP Status\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"unknown\",\"Link\":\"https://http.cat/\",\"Category\":\"Animals\"},{\"API\":\"IUCN\",\"Description\":\"IUCN Red List of Threatened Species\",\"Auth\":\"apiKey\",\"HTTPS\":false,\"Cors\":\"unknown\",\"Link\":\"http://apiv3.iucnredlist.org/api/v3/docs\",\"Category\":\"Animals\"},{\"API\":\"Movebank\",\"Description\":\"Movement and Migration data of animals\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"unknown\",\"Link\":\"https://github.com/movebank/movebank-api-doc\",\"Category\":\"Animals\"},{\"API\":\"Petfinder\",\"Description\":\"Adoption\",\"Auth\":\"apiKey\",\"HTTPS\":true,\"Cors\":\"unknown\",\"Link\":\"https://www.petfinder.com/developers/api-docs/\",\"Category\":\"Animals\"},{\"API\":\"RandomCat\",\"Description\":\"Random pictures of cats\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"yes\",\"Link\":\"https://aws.random.cat/meow\",\"Category\":\"Animals\"},{\"API\":\"RandomDog\",\"Description\":\"Random pictures of dogs\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"yes\",\"Link\":\"https://random.dog/woof.json\",\"Category\":\"Animals\"},{\"API\":\"RandomFox\",\"Description\":\"Random pictures of foxes\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"no\",\"Link\":\"https://randomfox.ca/floof/\",\"Category\":\"Animals\"},{\"API\":\"RescueGroups\",\"Description\":\"Adoption\",\"Auth\":\"\",\"HTTPS\":true,\"Cors\":\"unknown\",\"Link\":\"https://userguide.rescuegroups.org/display/APIDG/API+Developers+Guide+Home\",\"Category\":\"Animals\"},{\"API\":\"Shibe.Online\",\"Description\":\"Random pictures of Shibu Inu, cats or birds\",\"Auth\":\"\",\"HTTPS\":false,\"Cors\":\"no\",\"Link\":\"http://shibe.online/\",\"Category\":\"Animals\"}]}"

const val MOCK_CATEGORY_EMPTY_RESPONSE = "[]"

const val MOCK_CATEGORY_NOT_JSON = "invalid json"
